# Chicago Traffic Data

This is the notebook used to clean up the data used for this project. The original file was very large so it had to be seperated by year in order to be uploaded to github.

In [ ]:
# imports
import pandas as pd
from pathlib import Path
import datetime

# Original File

In [ ]:
# Assign file to variable
file = Path("../data/traffic_crashes.csv")

In [ ]:
# Create dataframe and view head
crash_data_df = pd.read_csv(file)
crash_data_df.head()

,CRASH_RECORD_ID,RD_NO,CRASH_DATE_EST_I,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,...,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION
0,012c5bfce715efb2f2b387d6dd86f9c13e9dc1809fb52a...,JG341943,NaN,07/12/2023 03:05:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,TURNING,...,0.0,0.0,2.0,0.0,15,4,7,41.778542,-87.742065,POINT (-87.742064741348 41.778541938106)
1,01d457f032e23d935a0b8f6b4c88221375180ffd4cd959...,JG338388,NaN,07/12/2023 05:50:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,REAR END,...,0.0,0.0,2.0,0.0,17,4,7,41.742131,-87.721824,POINT (-87.72182410033 41.742130554062)
2,02249b4747a4bf40b88a8357304a98dfeaef9c38eebbf0...,JG350008,NaN,07/12/2023 02:00:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,OTHER OBJECT,...,0.0,0.0,1.0,0.0,14,4,7,41.719844,-87.584790,POINT (-87.584789974824 41.719844228292)
3,03e3b6caad71b78ed9ae325648effa9512bfb2517aed30...,JG338049,NaN,07/12/2023 07:05:00 AM,30,TRAFFIC SIGNAL,UNKNOWN,FREEZING RAIN/DRIZZLE,DAYLIGHT,REAR END,...,0.0,0.0,2.0,0.0,7,4,7,41.925105,-87.668291,POINT (-87.668291181568 41.925104953308)
4,0481fc919b38f1572d4ba04b069766102d904a662ff096...,JG338431,NaN,07/12/2023 06:30:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,REAR END,...,0.0,0.0,2.0,0.0,18,4,7,41.975258,-87.751991,POINT (-87.751990557158 41.97525809527)

In [ ]:
# Check dataframe information
crash_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 746498 entries, 0 to 746497
Data columns (total 49 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   CRASH_RECORD_ID                746498 non-null  object
 1   RD_NO                          742191 non-null  object
 2   CRASH_DATE_EST_I               56389 non-null   object
 3   CRASH_DATE                     746498 non-null  object
 4   POSTED_SPEED_LIMIT             746498 non-null  int64
 5   TRAFFIC_CONTROL_DEVICE         746498 non-null  object
 6   DEVICE_CONDITION               746498 non-null  object
 7   WEATHER_CONDITION              746498 non-null  object
 8   LIGHTING_CONDITION             746498 non-null  object
 9   FIRST_CRASH_TYPE               746498 non-null  object
 10  TRAFFICWAY_TYPE                746498 non-null  object
 11  LANE_CNT                       199004 non-null  float64
 12  ALIGNMENT                      746498 non-null  object
 13  ROADWAY_SURFACE_COND           746498 non-null  object
 14  ROAD_DEFECT                    746498 non-null  object
 15  REPORT_TYPE                    725276 non-null  object
 16  CRASH_TYPE                     746498 non-null  object
 17  INTERSECTION_RELATED_I         171130 non-null  object
 18  NOT_RIGHT_OF_WAY_I             34774 non-null   object
 19  HIT_AND_RUN_I                  232792 non-null  object
 20  DAMAGE                         746498 non-null  object
 21  DATE_POLICE_NOTIFIED           746498 non-null  object
 22  PRIM_CONTRIBUTORY_CAUSE        746498 non-null  object
 23  SEC_CONTRIBUTORY_CAUSE         746498 non-null  object
 24  STREET_NO                      746498 non-null  int64
 25  STREET_DIRECTION               746494 non-null  object
 26  STREET_NAME                    746497 non-null  object
 27  BEAT_OF_OCCURRENCE             746493 non-null  float64
 28  PHOTOS_TAKEN_I                 9491 non-null    object
 29  STATEMENTS_TAKEN_I             16096 non-null   object
 30  DOORING_I                      2286 non-null    object
 31  WORK_ZONE_I                    4323 non-null    object
 32  WORK_ZONE_TYPE                 3370 non-null    object
 33  WORKERS_PRESENT_I              1115 non-null    object
 34  NUM_UNITS                      746498 non-null  int64
 35  MOST_SEVERE_INJURY             744868 non-null  object
 36  INJURIES_TOTAL                 744879 non-null  float64
 37  INJURIES_FATAL                 744879 non-null  float64
 38  INJURIES_INCAPACITATING        744879 non-null  float64
 39  INJURIES_NON_INCAPACITATING    744879 non-null  float64
 40  INJURIES_REPORTED_NOT_EVIDENT  744879 non-null  float64
 41  INJURIES_NO_INDICATION         744879 non-null  float64
 42  INJURIES_UNKNOWN               744879 non-null  float64
 43  CRASH_HOUR                     746498 non-null  int64
 44  CRASH_DAY_OF_WEEK              746498 non-null  int64
 45  CRASH_MONTH                    746498 non-null  int64
 46  LATITUDE                       741590 non-null  float64
 47  LONGITUDE                      741590 non-null  float64
 48  LOCATION                       741590 non-null  object
dtypes: float64(11), int64(6), object(32)
memory usage: 279.1+ MB

In [ ]:
# Reduce columns
cleaned_crash_data = crash_data_df[['RD_NO', 'CRASH_DATE', 'POSTED_SPEED_LIMIT', 'WEATHER_CONDITION', 'LIGHTING_CONDITION', 'FIRST_CRASH_TYPE', 'TRAFFICWAY_TYPE', 
                                    'ROADWAY_SURFACE_COND', 'ROAD_DEFECT', 'CRASH_TYPE', 'DAMAGE', 'PRIM_CONTRIBUTORY_CAUSE', 'SEC_CONTRIBUTORY_CAUSE', 'STREET_NAME', 
                                    'CRASH_HOUR', 'CRASH_DAY_OF_WEEK', 'CRASH_MONTH', 'LATITUDE', 'LONGITUDE', 'LOCATION']]
cleaned_crash_data.head()

,RD_NO,CRASH_DATE,POSTED_SPEED_LIMIT,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,ROADWAY_SURFACE_COND,ROAD_DEFECT,CRASH_TYPE,DAMAGE,PRIM_CONTRIBUTORY_CAUSE,SEC_CONTRIBUTORY_CAUSE,STREET_NAME,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION
0,JG341943,07/12/2023 03:05:00 PM,30,CLEAR,DAYLIGHT,TURNING,NOT DIVIDED,UNKNOWN,NO DEFECTS,NO INJURY / DRIVE AWAY,"OVER $1,500",IMPROPER TURNING/NO SIGNAL,UNABLE TO DETERMINE,63RD ST,15,4,7,41.778542,-87.742065,POINT (-87.742064741348 41.778541938106)
1,JG338388,07/12/2023 05:50:00 PM,30,CLEAR,DAYLIGHT,REAR END,NOT DIVIDED,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,"$501 - $1,500",FOLLOWING TOO CLOSELY,NOT APPLICABLE,PULASKI RD,17,4,7,41.742131,-87.721824,POINT (-87.72182410033 41.742130554062)
2,JG350008,07/12/2023 02:00:00 PM,30,CLEAR,DAYLIGHT,OTHER OBJECT,NOT DIVIDED,DRY,"RUT, HOLES",NO INJURY / DRIVE AWAY,"$501 - $1,500",NOT APPLICABLE,NOT APPLICABLE,STONY ISLAND AVE,14,4,7,41.719844,-87.584790,POINT (-87.584789974824 41.719844228292)
3,JG338049,07/12/2023 07:05:00 AM,30,FREEZING RAIN/DRIZZLE,DAYLIGHT,REAR END,NOT DIVIDED,UNKNOWN,UNKNOWN,NO INJURY / DRIVE AWAY,"$501 - $1,500",FOLLOWING TOO CLOSELY,UNABLE TO DETERMINE,ASHLAND AVE,7,4,7,41.925105,-87.668291,POINT (-87.668291181568 41.925104953308)
4,JG338431,07/12/2023 06:30:00 PM,30,CLEAR,DAYLIGHT,REAR END,NOT DIVIDED,WET,NO DEFECTS,NO INJURY / DRIVE AWAY,"OVER $1,500",FOLLOWING TOO CLOSELY,FOLLOWING TOO CLOSELY,ELSTON AVE,18,4,7,41.975258,-87.751991,POINT (-87.751990557158 41.97525809527)

In [ ]:
# Drop incomplete columns and check that columns have same amount of rows
cleaned_df = cleaned_crash_data.dropna()
cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 737324 entries, 0 to 746497
Data columns (total 20 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   RD_NO                    737324 non-null  object
 1   CRASH_DATE               737324 non-null  object
 2   POSTED_SPEED_LIMIT       737324 non-null  int64
 3   WEATHER_CONDITION        737324 non-null  object
 4   LIGHTING_CONDITION       737324 non-null  object
 5   FIRST_CRASH_TYPE         737324 non-null  object
 6   TRAFFICWAY_TYPE          737324 non-null  object
 7   ROADWAY_SURFACE_COND     737324 non-null  object
 8   ROAD_DEFECT              737324 non-null  object
 9   CRASH_TYPE               737324 non-null  object
 10  DAMAGE                   737324 non-null  object
 11  PRIM_CONTRIBUTORY_CAUSE  737324 non-null  object
 12  SEC_CONTRIBUTORY_CAUSE   737324 non-null  object
 13  STREET_NAME              737324 non-null  object
 14  CRASH_HOUR               737324 non-null  int64
 15  CRASH_DAY_OF_WEEK        737324 non-null  int64
 16  CRASH_MONTH              737324 non-null  int64
 17  LATITUDE                 737324 non-null  float64
 18  LONGITUDE                737324 non-null  float64
 19  LOCATION                 737324 non-null  object
dtypes: float64(2), int64(4), object(14)
memory usage: 118.1+ MB

In [ ]:
# Convert date to datetime
cleaned_df['CRASH_DATE'] = pd.to_datetime(cleaned_df['CRASH_DATE'])
cleaned_df.info()

/var/folders/b_/47k771614dlgjd4cqk_f_y180000gn/T/ipykernel_38118/825383330.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  cleaned_df['CRASH_DATE'] = pd.to_datetime(cleaned_df['CRASH_DATE'])
/var/folders/b_/47k771614dlgjd4cqk_f_y180000gn/T/ipykernel_38118/825383330.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_df['CRASH_DATE'] = pd.to_datetime(cleaned_df['CRASH_DATE'])

In [ ]:
# Order the accidents by date and select desired years
selected_years = [2018, 2019, 2020, 2021, 2022]
sorted_df = cleaned_df[cleaned_df['CRASH_DATE'].dt.year.isin(selected_years)]
sorted_df = sorted_df.sort_values(by='CRASH_DATE', ascending=True)
sorted_df.head()

,RD_NO,CRASH_DATE,POSTED_SPEED_LIMIT,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,ROADWAY_SURFACE_COND,ROAD_DEFECT,CRASH_TYPE,DAMAGE,PRIM_CONTRIBUTORY_CAUSE,SEC_CONTRIBUTORY_CAUSE,STREET_NAME,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION
718580,JB100559,2018-01-01 00:00:00,20,CLEAR,DAYLIGHT,PARKED MOTOR VEHICLE,NOT DIVIDED,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,"OVER $1,500",UNABLE TO DETERMINE,UNABLE TO DETERMINE,HARPER AVE,0,2,1,41.800575,-87.589225,POINT (-87.589225075066 41.80057461981)
13920,JB100868,2018-01-01 00:00:00,25,UNKNOWN,UNKNOWN,PARKED MOTOR VEHICLE,NOT DIVIDED,UNKNOWN,UNKNOWN,NO INJURY / DRIVE AWAY,"$501 - $1,500",UNABLE TO DETERMINE,UNABLE TO DETERMINE,117TH ST,0,2,1,41.681735,-87.641014,POINT (-87.641013916869 41.681735373094)
175227,JB100763,2018-01-01 00:00:00,30,CLEAR,UNKNOWN,PARKED MOTOR VEHICLE,ONE-WAY,UNKNOWN,UNKNOWN,NO INJURY / DRIVE AWAY,"$501 - $1,500",UNABLE TO DETERMINE,UNABLE TO DETERMINE,CUYLER AVE,0,2,1,41.955842,-87.650268,POINT (-87.65026813462 41.955842185147)
637953,JB100036,2018-01-01 00:05:00,30,CLEAR,"DARKNESS, LIGHTED ROAD",PARKED MOTOR VEHICLE,NOT DIVIDED,UNKNOWN,UNKNOWN,NO INJURY / DRIVE AWAY,"$501 - $1,500",UNABLE TO DETERMINE,UNABLE TO DETERMINE,ASHLAND AVE,0,2,1,41.949417,-87.668774,POINT (-87.66877431033 41.949417412921)
381931,JB100179,2018-01-01 00:07:00,35,SNOW,"DARKNESS, LIGHTED ROAD",PARKED MOTOR VEHICLE,NOT DIVIDED,SNOW OR SLUSH,NO DEFECTS,NO INJURY / DRIVE AWAY,"OVER $1,500",WEATHER,FAILING TO REDUCE SPEED TO AVOID CRASH,STATE ST,0,2,1,41.683946,-87.622993,POINT (-87.622993129041 41.683945885086)

In [ ]:
# Select desired columns
final_df = sorted_df[['CRASH_DATE', 'POSTED_SPEED_LIMIT', 'WEATHER_CONDITION', 'LIGHTING_CONDITION', 'FIRST_CRASH_TYPE', 
                                    'ROADWAY_SURFACE_COND', 'ROAD_DEFECT', 'CRASH_TYPE', 'DAMAGE', 'PRIM_CONTRIBUTORY_CAUSE', 'SEC_CONTRIBUTORY_CAUSE', 'STREET_NAME', 
                                    'CRASH_HOUR', 'CRASH_DAY_OF_WEEK', 'CRASH_MONTH', 'LATITUDE', 'LONGITUDE']]
final_df = final_df.reset_index(drop=True)
final_df.head()

,CRASH_DATE,POSTED_SPEED_LIMIT,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,ROADWAY_SURFACE_COND,ROAD_DEFECT,CRASH_TYPE,DAMAGE,PRIM_CONTRIBUTORY_CAUSE,SEC_CONTRIBUTORY_CAUSE,STREET_NAME,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE
0,2018-01-01 00:00:00,20,CLEAR,DAYLIGHT,PARKED MOTOR VEHICLE,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,"OVER $1,500",UNABLE TO DETERMINE,UNABLE TO DETERMINE,HARPER AVE,0,2,1,41.800575,-87.589225
1,2018-01-01 00:00:00,25,UNKNOWN,UNKNOWN,PARKED MOTOR VEHICLE,UNKNOWN,UNKNOWN,NO INJURY / DRIVE AWAY,"$501 - $1,500",UNABLE TO DETERMINE,UNABLE TO DETERMINE,117TH ST,0,2,1,41.681735,-87.641014
2,2018-01-01 00:00:00,30,CLEAR,UNKNOWN,PARKED MOTOR VEHICLE,UNKNOWN,UNKNOWN,NO INJURY / DRIVE AWAY,"$501 - $1,500",UNABLE TO DETERMINE,UNABLE TO DETERMINE,CUYLER AVE,0,2,1,41.955842,-87.650268
3,2018-01-01 00:05:00,30,CLEAR,"DARKNESS, LIGHTED ROAD",PARKED MOTOR VEHICLE,UNKNOWN,UNKNOWN,NO INJURY / DRIVE AWAY,"$501 - $1,500",UNABLE TO DETERMINE,UNABLE TO DETERMINE,ASHLAND AVE,0,2,1,41.949417,-87.668774
4,2018-01-01 00:07:00,35,SNOW,"DARKNESS, LIGHTED ROAD",PARKED MOTOR VEHICLE,SNOW OR SLUSH,NO DEFECTS,NO INJURY / DRIVE AWAY,"OVER $1,500",WEATHER,FAILING TO REDUCE SPEED TO AVOID CRASH,STATE ST,0,2,1,41.683946,-87.622993

### Seperate data by year and write to CSV

In [19]:
df_2018 = final_df[final_df['CRASH_DATE'].dt.year == 2018]
df_2019 = final_df[final_df['CRASH_DATE'].dt.year == 2019]
df_2020 = final_df[final_df['CRASH_DATE'].dt.year == 2020]
df_2021 = final_df[final_df['CRASH_DATE'].dt.year == 2021]
df_2022 = final_df[final_df['CRASH_DATE'].dt.year == 2022]

In [ ]:
df_2018.to_csv('../yearly_crash_data/df_2018.csv', index=False, header=True)
df_2019.to_csv('../yearly_crash_data/df_2019.csv', index=False, header=True)
df_2020.to_csv('../yearly_crash_data/df_2020.csv', index=False, header=True)
df_2021.to_csv('../yearly_crash_data/df_2021.csv', index=False, header=True)
df_2022.to_csv('../yearly_crash_data/df_2022.csv', index=False, header=True)